# Changes here will be overwritten by Copier
_commit: v1.4.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: ''
author_name: LF
create_example_module: false
custom_install: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: rail_notebooks
preferred_linter: none
project_license: none
project_name: rail_notebooks
use_gitlfs: none
use_isort: false
