# This workflow can be triggered manually; it will also run daily at 6:45 UTC.
# This workflow grabs globbed notebooks from the RAIL repository, runs them, and
# renders the notebooks with outputs into .rst files for easy integration into
# ReadTheDocs.
        
name: Render notebooks

on:
  workflow_dispatch:
  schedule:
    - cron: 45 6 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && install pandoc
        python -m pip install --upgrade pip
        pip install wheel numpy # For RAIL
        pip install jupyter nbconvert # For notebooks
        git clone https://github.com/LSSTDESC/rail.git
        cd rail
        pip install .[dev]
    - name: Run notebooks 
      run: |
        python render_notebooks.py core
        python render_notebooks.py creation
        python render_notebooks.py estimation
        python render_notebooks.py evaluation
        python render_notebooks.py goldenspike
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()
