# This workflow will run daily at 06:45.
# It will install Python dependencies and run tests with a variety of Python versions.
# See documentation for help debugging smoke test issues:
#    https://lincc-ppt.readthedocs.io/en/latest/practices/ci_testing.html#version-culprit

name: Unit test smoke test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python-version: ['3.8', '3.9', '3.10']
        python-version: ['3.10']
        #notebook-dir: ['core', 'creation', 'estimation', 'evaluation', 'goldenspike']
        #notebook-dir: ['core']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install wheel numpy
        git clone https://github.com/LSSTDESC/rail.git
        cd rail
        pip install .[dev]
    - name: List dependencies
      run: |
        pip list
    - name: Run notebooks
      run: |
        #rail render-nb docs/notebooks/*.ipynb
        #${{ matrix.notebook-dir }}
        #rail render-nb rail/examples/core_examples/*.ipynb docs/notebooks
        python -m render_script.py
        
    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()
